config/routes.rb
Rails.application.routes.draw do
  root "static_pages#workshop"

  controller :sessions do
    get "login" => :new
    post "login" => :create
    delete "logout" => :destroy
  end

  controller :static_pages do
    get "pages/privacy-policy" => :privacy
    get "pages/terms" => :terms
    get "pages/about" => :about
    get "workshop" => :workshop
  end

  post "/workshop_users", to: "users#create_workshop_users"

  get "/unsubscribe", to: "users#unsubscribe", as: :unsubscribe
  resources :users, only: [:index, :new, :create, :destroy] do
    collection do
      get :export
      get :download
      get :import
      post :upload
    end
  end
  resources :blogs, except: [:delete, :destroy]
  resources :tags, only: [:destroy]
  resources :emails, except: [:delete] do
    collection do
      post :send_daily_email
    end
  end
  get "/emails/:id/send_test_email", to: "emails#test_email", as: :test_email

  get "/blog", to: "blogs#index" # old path from kajabi app
  post "/blogs/search", to: "blogs#index", as: :blog_search
end

app/models/blog.rb
class Blog < ApplicationRecord
  has_many :tags, dependent: :destroy, inverse_of: :blog
  has_rich_text :content
  # used to query the attached ActionText directly
  has_one :action_text_rich_text, class_name: "ActionText::RichText", as: :record

  validates :title, presence: true

  scope :published, -> { where("published_at < ? AND is_draft = ?", Time.now, false) }

  before_save :format_named_url

  def id_for_url
    named_url.nil? ? id : named_url
  end

  private

  def format_named_url
    unless named_url.nil?
      formatted_named_url = named_url.strip.downcase.split.join("-")
      self.named_url = formatted_named_url.empty? ? nil : formatted_named_url
    end
  end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  include ActionView::Helpers::TextHelper

  before_action :set_blog, only: [:show, :edit]
  skip_before_action :authenticate_admin_user, only: [:index, :show]

  def index
    if @current_user&.can_manage_blogs?
      @blogs = Blog.includes(:tags).with_rich_text_content.order({ published_at: :desc })
      return render :admin
    end

    @blogs =
      if params[:tag].is_a? Array
        Blog.joins(:tags)
          .where("tags.text IN (?)", params[:tag])
          .distinct
      elsif params[:tag]
        Blog.joins(:tags)
          .where("tags.text = ?", params[:tag])
          .distinct
      elsif params[:q]
        Blog.joins(:tags, :action_text_rich_text)
          .where("lower(action_text_rich_texts.body) LIKE ?", "%#{params[:q].strip.downcase}%")
          .or(
            Blog.joins(:tags, :action_text_rich_text)
                .where("lower(blogs.title) LIKE ?", "%#{params[:q].strip.downcase}%")
          )
          .distinct
      else
        Blog.includes(:tags)
      end
        .published
        .order({ published_at: :desc })
        .with_rich_text_content
        .paginate(page: params[:page] || 1, per_page: 10)

    if params[:q] && @blogs.present?
      flash.now[:success] = "#{pluralize(@blogs.size, "result")} matching '#{params[:q].strip.downcase}'"
    elsif params[:q]
      flash.now[:notice] = "No blogs matched the phrase '#{params[:q].strip.downcase}'"
    end
  end

  def show
    redirect_to blogs_path if @blog.is_draft? && !@current_user&.can_manage_blogs?
  end

  def new
    @blog = Blog.new
  end

  def edit
    @tag = Tag.new
  end

  def create
    ActiveRecord::Base.transaction do
      blog = Blog.create!(blogs_params.except(:blog_tags))
      if blogs_params[:blog_tags]
        blogs_params[:blog_tags].split(",").each do |tag_text|
          Tag.create!(blog_id: blog.id, text: tag_text)
        end
      end
    end

    redirect_to blogs_path
  end

  def update
    ActiveRecord::Base.transaction do
      @blog = Blog.find(params[:id])
      @blog.update!(blogs_params.except(:blog_tags))
      if params[:blog][:tag]
        params[:blog][:tag][:text].split(",").each do |tag_text|
          Tag.create(text: tag_text, blog_id: @blog.id)
        end
      end
    end

    redirect_to blog_path(@blog)
  end

  private

  def set_blog
    @blog =
      if params[:id].to_i.to_s == params[:id]
        Blog.includes(:tags).find(params[:id])
      else
        Blog.includes(:tags).where(named_url: params[:id]).first
      end

    raise ActiveRecord::RecordNotFound unless @blog
  end

  def blogs_params
    params.require(:blog).permit(:title, :embedded_video, :published_at, :content, :named_url, :is_draft, :blog_tags, tag_attributes: [:text, :blog_id])
  end
end

app/helpers/blog_helper.rb
module BlogHelper
  def truncate_after_two_paragraphs(action_text_rich_text)
    Nokogiri::HTML::DocumentFragment.parse(action_text_rich_text.body.to_html).children[0..1].to_html
  end
end

app/views/blogs/_admin_blog.html.erb
<tr class="blog_<%= blog.id %>">
  <td>
    <%= link_to(blog.title, blog_path(blog), class: "has-text-link") %>
    <% if blog.is_draft %>
      <span class="tag is-danger">Draft</span>
    <% end %>
  </td>
  <td><%= blog.published_at.localtime.strftime("%B %-d, %Y") %></td>
  <td><%= link_to("Edit", edit_blog_path(blog), class: "has-text-link") %></td>
</tr>

app/views/blogs/_blog.html.erb
<div class="blog-container">
  <div class="blog">
    <h2 class="blog-title title is-1"><%= blog.title %></h2>
    <div class="has-text-grey sub-header">
      <% if blog.tags.size > 0 %>
        <div class="tags">
          <% blog.tags.each_with_index do |tag, index| %>
            <% if (index + 1) < blog.tags.size %>
              <%= link_to("#{tag.text},", blogs_path(tag: tag.text), class: "has-link-text")%>
            <% else %>
              <%= link_to("#{tag.text}", blogs_path(tag: tag.text), class: "has-link-text")%>
            <% end %>
          <% end %>
        </div>
      <% end %>
      <div class="published-at">
        <%= blog.published_at.localtime.strftime("%B %-d, %Y") %>
      </div>
    </div>
    <div class="blog-embedded-video">
      <%= raw blog.embedded_video %>
    </div>
    <div class="blog-content">
      <div class="trix-content">
        <%= raw(truncate_after_two_paragraphs(blog.content)) %>
      </div>
    </div>
    <div class="blog-details-link">
      <%= link_to("Continue reading...", blog_path(id: blog.id_for_url), class: "has-text-link") %>
    </div>
  </div>
</div>

app/views/blogs/admin.html.erb
<div class="blogs-admin-container">
  <div class="all-blogs">
    <h2 class="title is-4">All blogs</h2>
    <%= link_to(new_blog_path, class: "button is-info is-pulled-right is-small new-blog-button") do %>
      <span class="icon is-small">
        <i class="fas fa-plus"></i>
      </span>
      <span>New</span>
    <% end %>
    <table class="table is-fullwidth is-hoverable">
      <thead>
        <tr>
          <th>Title</th>
          <th>Published</th>
          <th>Edit</th>
        </tr>
      </thead>
      <tbody>
        <%= render(partial: 'blogs/admin_blog', collection: @blogs, as: :blog, cached: true) %>
      </tbody>
    </table>
  </div>
</div>

app/views/blogs/edit.html.erb
<div class="edit-blog">
  <div class="edit-blog-form-container">
    <h2 class="title is-4">Edit blog</h2>

    <%= form_with(model: @blog, url: blog_path(@blog)) do |f| %>
      <div class="field">
        <%= f.label :title %>
        <%= f.text_field :title, autocomplete: "off", class: "input" %>
      </div>

      <div class="field">
        <%= f.label :content %><br />
        <%= f.rich_text_area :content %>
      </div>

      <div class="field">
        <%= f.label :embedded_video %>
        <%= f.text_area :embedded_video, autocomplete: "off", class: "textarea" %>
      </div>

      <div class="field">
        <%= f.label :published_at %><br />
        <%= f.datetime_select :published_at, ampm: true, use_short_month: true, order: [:month, :day, :year], minute_step: 10, start_year: 2.years.ago.year %>
        <%#= f.datetime_field :published_at, min: 2.years.ago, max: 1.year.from_now %>
        <small class="has-text-grey-light">(USA Central Time)</small>
      </div>

      <div class="field">
        <%= f.label :named_url %>
        <%= f.text_field :named_url, autocomplete: "off", class: "input", placeholder: "cats-take-over-studio..." %>
      </div>

      <h2 class="title is-5 edit-tags-heading">Edit tags</h2>

      <ul class="tags">
        <%= render(@blog.tags, cached: true) %>
      </ul>

      <div class="new-tag-form">
        <%= f.fields_for :tag, @tag do |tag_attributes|%>
          <%= tag_attributes.hidden_field :blog_id, value: @blog.id %>
          <%= tag_attributes.text_field :text, placeholder: "Add comma separated tags...", autocomplete: "off", class: "input" %>
        <% end %>
      </div>

      <br/>

      <div class="field">
        <%= f.label "Save as draft" %>
        <%= f.check_box :is_draft %>
      </div>

      <div class="actions">
        <%= f.submit "Update", class: "button is-info" %>
        <%= link_to "Back", :back, class: "button is-info is-outlined" %>
      </div>
    <% end %>
  </div>
</div>

app/views/blogs/index.html.erb
<div class="blogs">
  <% cache(@blogs) do %>
    <%= render(partial: 'blogs/blog', collection: @blogs, cached: true) %>

    <div class="pagination-container">
      <%= will_paginate(@blogs, renderer: BulmaPagination::Rails, class: 'is-centered', maximum_links: 2) %>
    </div>
  <% end %>

  <div class="search-input-container">
    <%= form_with(url: blogs_path, method: :get, local: true, class: "blog-search-form") do |f| %>
      <p class="control has-icons-left">
        <input class="input" name="q" type="search" placeholder="Search blog content..." autocomplete="off">
        <span class="icon is-small is-left">
          <%= fa_icon("search", class: "fas") %>
        </span>
        <%= f.submit "Search", name: nil, class: "button is-link is-outlined blog-search-button" %>
      </p>
    <% end %>
  </div>
</div>

app/views/blogs/new.html.erb
<div class="new-blog">
  <div class="new-blog-form-container">
    <h2 class="title is-4">New blog</h2>

    <%= form_with(model: @blog, url: blogs_path) do |f| %>
      <div class="field">
        <%= f.label :title %>
        <%= f.text_field :title, autocomplete: "off", class: "input" %>
      </div>

      <div class="field">
        <%= f.label :content %><br />
        <%= f.rich_text_area :content %>
      </div>

      <div class="field">
        <%= f.label :embedded_video %>
        <%= f.text_area :embedded_video, autocomplete: "off", class: "textarea" %>
      </div>

      <div class="field">
        <%= f.label :published_at %><br />
        <%= f.datetime_select :published_at, ampm: true, use_short_month: true, order: [:month, :day, :year], minute_step: 10, start_year: 2.years.ago.year %>
        <%#= f.datetime_field :published_at, min: 2.years.ago, max: 1.year.from_now %>
        <small class="has-text-grey-light">(USA Central Time)</small>
      </div>

      <div class="field">
        <%= f.label :named_url %>
        <%= f.text_field :named_url, autocomplete: "off", class: "input", placeholder: "cats-take-over-studio..." %>
      </div>

      <div class="field">
        <%= f.label :blog_tags %>
        <%= f.text_field :blog_tags, autocomplete: "off", class: "input", placeholder: "Add comma separated tags..." %>
      </div>

      <div class="field">
        <%= f.label "Save as draft" %>
        <%= f.check_box :is_draft %>
      </div>

      <div class="actions">
        <%= f.submit "Create", class: "button is-info" %>
        <%= link_to "Back", blogs_path, class: "button is-info is-outlined" %>
      </div>
    <% end %>
  </div>
</div>

app/views/blogs/show.html.erb
<div class="blog-details">
  <div class="blog-container">
    <div class="blog">
      <% if @current_user&.can_manage_blogs? && @blog.is_draft? %>
        <p class="tag is-danger is-pulled-right">DRAFT</p>
      <% end %>
      <h2 class="blog-title title is-1"><%= @blog.title %></h2>
      <% if @current_user&.can_manage_blogs? %>
        <div class="edit-blog-link">
          <%= link_to(edit_blog_path(@blog), class: "button is-warning is-small") do %>
            <span class="icon is-small">
              <i class="fas fa-pen"></i>
            </span>
            <span>Edit</span>
          <% end %>
        </div>
      <% end %>
      <div class="has-text-grey sub-header">
        <% if @blog.tags.size > 0 %>
          <div class="tags">
            <% @blog.tags.each_with_index do |tag, index| %>
              <% if (index + 1) < @blog.tags.size %>
                <%= link_to("#{tag.text},", blogs_path(tag: tag.text), class: "has-link-text")%>
              <% else %>
                <%= link_to("#{tag.text}", blogs_path(tag: tag.text), class: "has-link-text")%>
              <% end %>
            <% end %>
          </div>
        <% end %>
        <div class="published-at">
          <%= @blog.published_at.localtime.strftime("%B %-d, %Y") %>
        </div>
      </div>
      <div class="blog-embedded-video"><%= raw @blog.embedded_video %></div>
      <div class="blog-content"><%= @blog.content %></div>
    </div>
  </div>

  <div class="lower-cards-container">
    <div class="card-columns columns">
      <div class="author-details has-text-centered column">
        <p><strong>About the author:</strong></p>
        <%= image_tag("author.jpg", class: "author-image") %>
        <p>Josh Jones is a musician, producer, engineer,</p>
        <p> online educator, and heavy music fan.</p>
      </div>
      <div class="workshop-details has-text-centered column">
        <div><%= image_tag("workshop_banner.jpg", class: "workshop-banner") %></div>
        <%= link_to("Watch the free workshop", workshop_path, class: "button is-info") %>
        <p>Learn twelve of the most important decisions</p>
        <p>behind every great music creation success.</p>
      </div>
    </div>
  </div>
</div>