config/routes.rb
Rails.application.routes.draw do
  root "static_pages#workshop"

  controller :sessions do
    get "login" => :new
    post "login" => :create
    delete "logout" => :destroy
  end

  controller :static_pages do
    get "pages/privacy-policy" => :privacy
    get "pages/terms" => :terms
    get "pages/about" => :about
    get "workshop" => :workshop
  end

  post "/workshop_users", to: "users#create_workshop_users"

  get "/unsubscribe", to: "users#unsubscribe", as: :unsubscribe
  resources :users, only: [:index, :new, :create, :destroy] do
    collection do
      get :export
      get :download
      get :import
      post :upload
    end
  end
  resources :blogs, except: [:delete, :destroy]
  resources :tags, only: [:destroy]
  resources :emails, except: [:delete] do
    collection do
      post :send_daily_email
    end
  end
  get "/emails/:id/send_test_email", to: "emails#test_email", as: :test_email

  get "/blog", to: "blogs#index" # old path from kajabi app
  post "/blogs/search", to: "blogs#index", as: :blog_search
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  encrypts :name
  encrypts :email, deterministic: true, downcase: true

  validates :email, presence: true, uniqueness: true
  validates :name, presence: true
  validates :password, presence: true, confirmation: true, if: :password
  validate :site_role_valid

  SITE_USER = "user".freeze
  SITE_ADMIN = "admin".freeze
  USER_SITE_ROLES = [SITE_USER, SITE_ADMIN].freeze

  def is_admin?
    site_role == SITE_ADMIN
  end

  def can_manage_users?
    is_admin?
  end

  def can_manage_emails?
    is_admin?
  end

  def can_manage_blogs?
    is_admin?
  end

  def just_created?
    saved_change_to_attribute?(:id)
  end

  def unsubscribe_key
    Rails.application.message_verifier(:unsubscribe).generate({
      id: id,
      created_at: Time.now.utc.to_s
    })
  end

  def workshop_key
    Rails.application.message_verifier(:workshop).generate({
      id: id,
      created_at: Time.now.utc.to_s
    })
  end

  def self.find_or_create_workshop_user(name:, email:)
    temp_password = SecureRandom.hex
    create_with(
      name: name,
      password: temp_password,
      password_confirmation: temp_password
    ).find_or_create_by(email: email)
  end

  # Returns a user or nil
  def self.find_by_unsubscribe_key(unsubscribe_key)
    decrypted = Rails.application.message_verifier(:unsubscribe).verify(unsubscribe_key)
    user_id = decrypted.is_a?(Hash) ? decrypted.fetch(:id) : decrypted
    find_by(id: user_id)
  rescue ActiveSupport::MessageVerifier::InvalidSignature
    nil
  end

  # Returns a User or nil
  def self.find_by_workshop_key(workshop_key)
    decrypted = Rails.application.message_verifier(:workshop).verify(workshop_key)
    user_id = decrypted.is_a?(Hash) ? decrypted.fetch(:id) : decrypted
    find_by(id: user_id)
  rescue ActiveSupport::MessageVerifier::InvalidSignature
    nil
  end

  private

  def site_role_valid
    unless USER_SITE_ROLES.include?(site_role)
      errors.add(:site_role, "not included in '#{USER_SITE_ROLES}'")
    end
  end
end

app/controllers/users_controller.rb
require "csv"

class UsersController < ApplicationController
  include DateParsing

  class InsecureRequest < StandardError; end
  class NoUnsubscribeUserFound < StandardError; end

  skip_before_action :authenticate_admin_user, only: [:create_workshop_users, :unsubscribe, :destroy]

  ORDERED_CSV_FIELDS = [
    :name,
    :email,
    :site_role,
    :workshop_page_views,
    :created_at,
    :updated_at
  ]

  def index
    @users = User.where(site_role: User::SITE_USER).order({ created_at: :desc })
  end

  def new
    @user = User.new
  end

  def create
    user = User.find_or_create_workshop_user(name: user_params[:name], email: user_params[:email])
    user.just_created? ? flash[:success] = "User added" : flash[:notice] = "User already exists"
    redirect_to new_user_path
  end

  def unsubscribe
    # Handle unsubscribe key provided via URL params first
    if params[:id]
      @user = User.find_by_unsubscribe_key(params[:id])
      raise NoUnsubscribeUserFound unless @user
      session[:user_id] = @user.id
      # TODO: Still losing the session on redirect somehow, so I don't think this will work 🤔
      # return redirect_to unsubscribe_path, status: :see_other
    end

    @user = User.find(session[:user_id])
  rescue ActiveRecord::RecordNotFound, NoUnsubscribeUserFound
    reset_session
    flash[:notice] = "We couldn't find you! You are either already unsubscribed, or you'll need to follow the unsubscribe link from your email again."
    redirect_to workshop_path
  end

  def create_workshop_users
    user = User.find_or_create_workshop_user(name: user_params[:name], email: user_params[:email])
    if user.is_admin?
      reset_session
      redirect_to login_url
    else
      session[:user_id] = user.id
      UserMailer.workshop_email(user.id).deliver_later
      redirect_to workshop_path
    end
  end

  def destroy
    # user is authenticated automatically when they go to the unsubscribe page
    @authenticated_user = @current_user
    @user_to_delete = User.find(params[:id])
    secure_request!
    @user_to_delete.destroy!

    return respond_to(&:turbo_stream) if @authenticated_user.is_admin?

    reset_session
    flash[:notice] = "You have successfully unsubscribed."
    # https://github.com/hotwired/turbo-rails/issues/122#issuecomment-782766453
    redirect_to workshop_path, status: :see_other
  rescue
    if @authenticated_user
      flash[:alert] = "Something went wrong! Please try again."
      redirect_to unsubscribe_path(id: @authenticated_user.unsubscribe_key)
    else
      flash[:alert] = "Something went wrong! Please follow the unsubscribe link from your email again."
      redirect_to workshop_path
    end
  end

  def export
  end


  def import
  end

  def download
    csv = CSV.generate(headers: true) do |csv|
      csv << ORDERED_CSV_FIELDS # add headers

      User.find_each do |user|
        csv << ORDERED_CSV_FIELDS.map { |attr| user.send(attr) }
      end
    end

    respond_to do |format|
      format.csv { send_data(csv, filename: "users_export_#{Time.now.utc.to_i}.csv") }
    end
  end

  def upload
    unless params[:csv_file]&.content_type == "text/csv"
      return redirect_to import_users_path, alert: "Missing CSV file or unsupported file format"
    end

    users_added = 0
    users_updated = 0
    users_already_exist = 0
    admins_skipped = 0
    CSV.read(params[:csv_file].path).each_with_index do |row, index|
      if index.zero?
        return redirect_to import_users_path, alert: "Incorrectly formatted CSV" if row.size != ORDERED_CSV_FIELDS.size
        next if params[:csv_includes_headers]
      end

      name = row[0]
      email = row[1]
      site_role = User::SITE_USER # don't allow users to be made admins with user import
      workshop_page_views = row[3].presence || 0
      created_at = row[4].presence && date_or_time_from(row[4])
      updated_at = row[5].presence && date_or_time_from(row[5])

      if (user = User.find_by(email: email))
        if user.is_admin?
          # don't accidentally overwrite admin users
          admins_skipped +=1
        elsif params[:overwrite_matching_users]
          users_updated += 1 if user.update(
            name: name,
            site_role: site_role,
            workshop_page_views: workshop_page_views,
            created_at: created_at,
            updated_at: updated_at
          )
        end

        next users_already_exist += 1
      end

      temp_password = SecureRandom.hex
      users_added += 1 if User.create(
        name: name,
        email: email,
        site_role: site_role,
        workshop_page_views: workshop_page_views,
        created_at: created_at,
        updated_at: updated_at,
        password: temp_password,
        password_confirmation: temp_password
      )
    end

    flash[:success] =
      if params[:overwrite_matching_users]
        "#{users_updated} existing #{"user".pluralize(users_updated)} updated, #{users_added} new #{"user".pluralize(users_added)} imported, #{admins_skipped} #{"admin".pluralize(admins_skipped)} skipped."
      else
        "#{users_added} new #{"user".pluralize(users_added)} imported, #{users_already_exist} #{"user".pluralize(users_already_exist)} already #{"exist".pluralize(users_added)}."
      end
    redirect_to users_path
  rescue InvalidDateOrTime => error
    redirect_to import_users_path, alert: "Some users were unable to be imported: invalid date format: '#{error.message}'. Please use 'mm/dd/yyyy' formatted dates."
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def secure_request!
    unless @authenticated_user.is_admin? || (@user_to_delete == @authenticated_user)
      raise InsecureRequest
    end
  end
end

app/views/users/_user.html.erb
<tr id="<%= dom_id(user) %>">
  <td><%= user.name %></td>
  <td><%= user.email %></td>
  <td><%= user.created_at.localtime.strftime("%B %-d, %Y") %></td>
  <td><%= user.workshop_page_views %></td>
  <td class="delete-user-row">
    <%= link_to("Delete", user_path(user), method: :delete, class: "has-text-link", data: { turbo_method: "delete", turbo_confirm: "Are you sure you want to delete user '#{user.email}'? This action is permanent and cannot be undone." }) %>
  </td>
</tr>

app/views/users/destroy.turbo_stream.erb
<%= turbo_stream.remove @user_to_delete %>

app/views/users/export.html.erb
<div class="static-page-container">
  <div class="static-page-content">
    <h1 class="title is-4">Export your users</h1>

    <p>
      Download a CSV of your user list for data backup or to use in another tool.
    </p>

    <div class="actions">
      <%= link_to(download_users_path(format: :csv), target: "_blank", rel: "noopener noreferrer", class: "button is-info") do %>
        Download all users
      <% end %>
    </div>
  </div>
</div>

app/views/users/import.html.erb
<div class="static-page-container">
  <div class="static-page-content">
    <h1 class="title is-4">Import users</h1>

    <p>
      Prepare a CSV of users to import. The CSV collums will need to exactly match the following format. The first two columns are <strong>required</strong> to be present and the remaining columns may be left blank if desired.
    </p>

    <ul class="csv-format">
      <li>[0]<strong>Name</strong></li>
      <li>[1]<strong>Email</strong></li>
      <li>[2]Site role</li>
      <li>[3]Workshop page views</li>
      <li>[4]Created at (mm/dd/yyyy)</li>
      <li>[5]Updated at (mm/dd/yyyy)</li>
    </ul>
    <%= form_tag(upload_users_path, method: :post, multipart: true, class: "import-csv-form") do %>
      <%= file_field_tag :csv_file %>

      <div class="includes-headers-field-row">
        <%= label_tag :csv_includes_headers, class: "switch", tabindex: "-1" do %>
          <%= check_box_tag :csv_includes_headers, true, true %>
          <span class="slider round"></span>
        <% end %>
        <span class="label-text">CSV includes headers</span>
      </div>

      <p class="inner-form-instructions">
        The import tool will prevent the creation of duplicate users based on the first two columns of the CSV. You may also use this tool to <em>update</em> existing users for easier bulk changes.
      </p>

      <div class="overwrite-matching-users-field-row">
        <%= label_tag :overwrite_matching_users, class: "switch", tabindex: "-1" do %>
          <%= check_box_tag :overwrite_matching_users, true, false %>
          <span class="slider round"></span>
        <% end %>
        <span class="label-text">Overwrite matching users</span>
      </div>

      <%= submit_tag("Import users", class: "button is-info", data: { controller: "disable", disable_with_value: "Importing...", action: "disable#disableButton", disable_target: "button" }) %>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<div class="all-users">
  <div class="all-users-container">
    <h2 class="title is-4">All site users</h1>

    <div class="actions">
      <%= link_to(new_user_path, class: "button is-info is-small") do %>
        <span class="icon is-small">
          <i class="fas fa-plus"></i>
        </span>
        <span>New</span>
      <% end %>
      <%= link_to(import_users_path, class: "button is-info is-small desktop-action") do %>
        <span class="icon is-small">
          <i class="fas fa-file-upload"></i>
        </span>
        <span>Import</span>
      <% end %>
      <%= link_to(export_users_path, class: "button is-info is-small") do %>
        <span class="icon is-small">
          <i class="fas fa-file-download"></i>
        </span>
        <span>Export</span>
      <% end %>
    </div>

    <p class="has-text-grey-light users-total">Total: <%= @users.size %></p>

    <table class="table is-fullwidth is-hoverable">
      <thead>
        <tr>
          <th>Name</th>
          <th>Email</th>
          <th>Joined</th>
          <th class="views-column-sm">
            <span class="icon is-small">
              <i class="far fa-eye"></i>
            </span>
          </th>
          <th class="views-column-lg">Workshop views</th>
          <th class="delete-user-header">Delete</th>
        </tr>
      </thead>
      <tbody>
        <%= render(partial: "users/user", collection: @users, cached: true) %>
      </tbody>
    </table>
  </div>
</div>

app/views/users/new.html.erb
<div class="new-user">
  <div class="new-user-form-container">
    <br/>
    <h2 class="title is-4">Manually add a site user</h2>
    <%= form_with(model: @user, url: users_path) do |f| %>
      <div class="field">
        <p class="control has-icons-left">
          <input class="input" type="text" placeholder="Name" name="user[name]">
          <span class="icon is-small is-left">
            <i class="fas fa-user"></i>
          </span>
        </p>
      </div>

      <div class="field">
        <p class="control has-icons-left">
          <input class="input" type="email" placeholder="Email" name="user[email]">
          <span class="icon is-small is-left">
            <i class="fas fa-envelope"></i>
          </span>
        </p>
      </div>

      <div class="actions">
        <%= f.submit "Add user", class: "button is-info" %>
        <%= link_to("Back", :back, class: "button is-info is-outlined") %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/new_workshop_user.html.erb
<div class="new-workshop-user">
  <div class="overlay">
    <div class="sign-up-card">
      <h2 class="title is-3 has-text-white">
        I Want To Help You Create the Best Rock And Heavy Music Of Your Career
      </h2>
      <p class="has-text-white is-size-5">
        Learn twelve key decisions you can make today to take your writing, recording, mixing, and live performances to the next level.
      </p>

      <div class="inner-sign-up-card has-text-centered">
        <h2 class="title is-4 has-text-black">
          Sign up to get immediate access to the free video workshop!
        </h2>
        <%= form_with(model: @user, url: workshop_users_path) do |f| %>
          <div class="field">
            <p class="control has-icons-left">
              <input class="input" type="text" placeholder="Name" name="user[name]">
              <span class="icon is-small is-left">
                <i class="fas fa-user"></i>
              </span>
            </p>
          </div>

          <div class="field">
            <p class="control has-icons-left">
              <input class="input" type="email" placeholder="Email" name="user[email]">
              <span class="icon is-small is-left">
                <i class="fas fa-envelope"></i>
              </span>
            </p>
          </div>

          <p class="has-text-grey subtitle">
            Get a unique link to your workshop today! You may choose to unsubscribe at any time.
          </p>

          <div class="actions">
            <%= f.submit "Watch the free workshop", class: "button is-info" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/unsubscribe.html.erb
<div class="static-page-container">
  <div class="static-page-content content">
    <h2 class="title is-4">👋 Unsubscribe</h2>
    <p>Are you sure you want to unsubscribe from musiclikeyoumeanit.com? This action will permanently delete all your user data and cannot be undone.</p>
    <%= link_to("Unsubscribe", user_path(@user), method: :delete, class: "button is-warning", data: { "turbo-method" => "delete" }) %>
  </div>
</div>