config/routes.rb
Rails.application.routes.draw do
  root "static_pages#workshop"

  controller :sessions do
    get "login" => :new
    post "login" => :create
    delete "logout" => :destroy
  end

  controller :static_pages do
    get "pages/privacy-policy" => :privacy
    get "pages/terms" => :terms
    get "pages/about" => :about
    get "workshop" => :workshop
  end

  post "/workshop_users", to: "users#create_workshop_users"

  get "/unsubscribe", to: "users#unsubscribe", as: :unsubscribe
  resources :users, only: [:index, :new, :create, :destroy] do
    collection do
      get :export
      get :download
      get :import
      post :upload
    end
  end
  resources :blogs, except: [:delete, :destroy]
  resources :tags, only: [:destroy]
  resources :emails, except: [:delete] do
    collection do
      post :send_daily_email
    end
  end
  get "/emails/:id/send_test_email", to: "emails#test_email", as: :test_email

  get "/blog", to: "blogs#index" # old path from kajabi app
  post "/blogs/search", to: "blogs#index", as: :blog_search
end

app/models/tag.rb
class Tag < ApplicationRecord
  belongs_to :blog, touch: true, inverse_of: :tags

  validates :text, presence: true

  before_save :format_text

  private

  def format_text
    self.text = text.strip.capitalize
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def destroy
    @tag = Tag.find(params[:id])
    @tag.destroy
    respond_to(&:turbo_stream)
  end

  private

  def tag_params
    params.require(:tag).permit(:text, :blog_id)
  end
end

app/views/tags/_tag.html.erb
<%= turbo_frame_tag dom_id(tag) do %>
  <li class="blog-tag tag_<%= tag.id %>">
    <span><%= tag.text %></span>
    <strong class="resource-action-divider has-text-link">|</strong>
    <%= link_to("Delete", tag_path(tag), method: :delete, class: "has-text-link", data: { turbo_method: "delete", turbo_confirm: "Are you sure you want to delete the '#{tag.text}' tag? This action is permanent." }) %>
  </li>
<% end %>

app/views/tags/destroy.turbo_stream.erb
<%= turbo_stream.remove @tag %>